layers = [
    "1 Echtzeit-Datenaufnahme (Real-Time Ingestion)",
    "2 Batch-Ingestion & ETL/ELT",
    "3 Konnektoren-Ökosystem & Marketplace",
    "4 Data-Lakehouse-Architektur",
    "5 Datenformat-Flexibilität",
    "6 Storage-Tiering & Lifecycle-Management",
    "7 Skalierbarkeit (Compute & Storage)",
    "8 Stream-Processing & Complex Event Processing",
    "9 Analytische Query-Engine",
    "10 BI- & Visualisierungs-Integration",
    "11 Ad-hoc-Exploration & Notebooks",
    "12 ML-Plattform & AutoML",
    "13 MLOps, Modell-Lifecycle & Reproduzierbarkeit",
    "14 Feature Store",
    "15 Generative AI & LLM-Integration",
    "16 Modell-Erklärbarkeit & Fairness",
    "17 Data Governance, Katalogisierung, Metadaten & Lineage",
    "18 Datenqualitätsmanagement",
    "19 Sicherheitsarchitektur & Zugriffskontrolle",
    "20 Resilienz & Disaster Recovery",
    "21 Edge-Computing & lokale Verarbeitung",
    "22 Multi-Cloud, Hybrid & Portabilität",
    "23 Infrastructure as Code & DataOps",
    "24 Monitoring, Observability & AIOps",
    "25 API-First & Entwicklerfreundlichkeit",
    "26 Cross-Organization Data Sharing",
]

scores = {
    "AWS": {
        "1 Echtzeit-Datenaufnahme (Real-Time Ingestion)": 5.0,
        "2 Batch-Ingestion & ETL/ELT": 5.0,
        "3 Konnektoren-Ökosystem & Marketplace": 5.0,
        "4 Data-Lakehouse-Architektur": 5.0,
        "5 Datenformat-Flexibilität": 5.0,
        "6 Storage-Tiering & Lifecycle-Management": 5.0,
        "7 Skalierbarkeit (Compute & Storage)": 5.0,
        "8 Stream-Processing & Complex Event Processing": 5.0,
        "9 Analytische Query-Engine": 5.0,
        "10 BI- & Visualisierungs-Integration": 5.0,
        "11 Ad-hoc-Exploration & Notebooks": 5.0,
        "12 ML-Plattform & AutoML": 5.0,
        "13 MLOps, Modell-Lifecycle & Reproduzierbarkeit": 5.0,
        "14 Feature Store": 5.0,
        "15 Generative AI & LLM-Integration": 4.0,
        "16 Modell-Erklärbarkeit & Fairness": 4.0,
        "17 Data Governance, Katalogisierung, Metadaten & Lineage": 4.0,
        "18 Datenqualitätsmanagement": 3.0,
        "19 Sicherheitsarchitektur & Zugriffskontrolle": 5.0,
        "20 Resilienz & Disaster Recovery": 5.0,
        "21 Edge-Computing & lokale Verarbeitung": 5.0,
        "22 Multi-Cloud, Hybrid & Portabilität": 3.0,
        "23 Infrastructure as Code & DataOps": 5.0,
        "24 Monitoring, Observability & AIOps": 5.0,
        "25 API-First & Entwicklerfreundlichkeit": 4.0,
        "26 Cross-Organization Data Sharing": 4.0,
    },
    "Azure": {
        "1 Echtzeit-Datenaufnahme (Real-Time Ingestion)": 5.0,
        "2 Batch-Ingestion & ETL/ELT": 5.0,
        "3 Konnektoren-Ökosystem & Marketplace": 5.0,
        "4 Data-Lakehouse-Architektur": 5.0,
        "5 Datenformat-Flexibilität": 5.0,
        "6 Storage-Tiering & Lifecycle-Management": 5.0,
        "7 Skalierbarkeit (Compute & Storage)": 5.0,
        "8 Stream-Processing & Complex Event Processing": 5.0,
        "9 Analytische Query-Engine": 5.0,
        "10 BI- & Visualisierungs-Integration": 5.0,
        "11 Ad-hoc-Exploration & Notebooks": 5.0,
        "12 ML-Plattform & AutoML": 5.0,
        "13 MLOps, Modell-Lifecycle & Reproduzierbarkeit": 5.0,
        "14 Feature Store": 4.0,
        "15 Generative AI & LLM-Integration": 5.0,
        "16 Modell-Erklärbarkeit & Fairness": 4.0,
        "17 Data Governance, Katalogisierung, Metadaten & Lineage": 4.0,
        "18 Datenqualitätsmanagement": 3.0,
        "19 Sicherheitsarchitektur & Zugriffskontrolle": 5.0,
        "20 Resilienz & Disaster Recovery": 5.0,
        "21 Edge-Computing & lokale Verarbeitung": 5.0,
        "22 Multi-Cloud, Hybrid & Portabilität": 3.0,
        "23 Infrastructure as Code & DataOps": 5.0,
        "24 Monitoring, Observability & AIOps": 5.0,
        "25 API-First & Entwicklerfreundlichkeit": 4.0,
        "26 Cross-Organization Data Sharing": 4.0,
    },
    "Google Cloud": {
        "1 Echtzeit-Datenaufnahme (Real-Time Ingestion)": 4.0,
        "2 Batch-Ingestion & ETL/ELT": 5.0,
        "3 Konnektoren-Ökosystem & Marketplace": 5.0,
        "4 Data-Lakehouse-Architektur": 5.0,
        "5 Datenformat-Flexibilität": 5.0,
        "6 Storage-Tiering & Lifecycle-Management": 5.0,
        "7 Skalierbarkeit (Compute & Storage)": 5.0,
        "8 Stream-Processing & Complex Event Processing": 5.0,
        "9 Analytische Query-Engine": 5.0,
        "10 BI- & Visualisierungs-Integration": 5.0,
        "11 Ad-hoc-Exploration & Notebooks": 5.0,
        "12 ML-Plattform & AutoML": 5.0,
        "13 MLOps, Modell-Lifecycle & Reproduzierbarkeit": 5.0,
        "14 Feature Store": 5.0,
        "15 Generative AI & LLM-Integration": 5.0,
        "16 Modell-Erklärbarkeit & Fairness": 5.0,
        "17 Data Governance, Katalogisierung, Metadaten & Lineage": 5.0,
        "18 Datenqualitätsmanagement": 4.0,
        "19 Sicherheitsarchitektur & Zugriffskontrolle": 5.0,
        "20 Resilienz & Disaster Recovery": 5.0,
        "21 Edge-Computing & lokale Verarbeitung": 4.0,
        "22 Multi-Cloud, Hybrid & Portabilität": 5.0,
        "23 Infrastructure as Code & DataOps": 5.0,
        "24 Monitoring, Observability & AIOps": 5.0,
        "25 API-First & Entwicklerfreundlichkeit": 5.0,
        "26 Cross-Organization Data Sharing": 5.0,
    },
    "STACKIT": {
        "1 Echtzeit-Datenaufnahme (Real-Time Ingestion)": 2.0,
        "2 Batch-Ingestion & ETL/ELT": 2.0,
        "3 Konnektoren-Ökosystem & Marketplace": 1.0,
        "4 Data-Lakehouse-Architektur": 1.0,
        "5 Datenformat-Flexibilität": 2.0,
        "6 Storage-Tiering & Lifecycle-Management": 2.0,
        "7 Skalierbarkeit (Compute & Storage)": 3.0,
        "8 Stream-Processing & Complex Event Processing": 1.0,
        "9 Analytische Query-Engine": 2.0,
        "10 BI- & Visualisierungs-Integration": 2.0,
        "11 Ad-hoc-Exploration & Notebooks": 2.0,
        "12 ML-Plattform & AutoML": 2.0,
        "13 MLOps, Modell-Lifecycle & Reproduzierbarkeit": 1.0,
        "14 Feature Store": 1.0,
        "15 Generative AI & LLM-Integration": 2.0,
        "16 Modell-Erklärbarkeit & Fairness": 1.0,
        "17 Data Governance, Katalogisierung, Metadaten & Lineage": 2.0,
        "18 Datenqualitätsmanagement": 1.0,
        "19 Sicherheitsarchitektur & Zugriffskontrolle": 4.0,
        "20 Resilienz & Disaster Recovery": 3.0,
        "21 Edge-Computing & lokale Verarbeitung": 2.0,
        "22 Multi-Cloud, Hybrid & Portabilität": 4.0,
        "23 Infrastructure as Code & DataOps": 4.0,
        "24 Monitoring, Observability & AIOps": 3.0,
        "25 API-First & Entwicklerfreundlichkeit": 2.0,
        "26 Cross-Organization Data Sharing": 1.0,
    },
    "IONOS": {
        "1 Echtzeit-Datenaufnahme (Real-Time Ingestion)": 2.0,
        "2 Batch-Ingestion & ETL/ELT": 2.0,
        "3 Konnektoren-Ökosystem & Marketplace": 2.0,
        "4 Data-Lakehouse-Architektur": 1.0,
        "5 Datenformat-Flexibilität": 2.0,
        "6 Storage-Tiering & Lifecycle-Management": 2.0,
        "7 Skalierbarkeit (Compute & Storage)": 3.0,
        "8 Stream-Processing & Complex Event Processing": 1.0,
        "9 Analytische Query-Engine": 1.0,
        "10 BI- & Visualisierungs-Integration": 1.0,
        "11 Ad-hoc-Exploration & Notebooks": 2.0,
        "12 ML-Plattform & AutoML": 2.0,
        "13 MLOps, Modell-Lifecycle & Reproduzierbarkeit": 1.0,
        "14 Feature Store": 1.0,
        "15 Generative AI & LLM-Integration": 2.0,
        "16 Modell-Erklärbarkeit & Fairness": 1.0,
        "17 Data Governance, Katalogisierung, Metadaten & Lineage": 2.0,
        "18 Datenqualitätsmanagement": 1.0,
        "19 Sicherheitsarchitektur & Zugriffskontrolle": 3.0,
        "20 Resilienz & Disaster Recovery": 3.0,
        "21 Edge-Computing & lokale Verarbeitung": 1.0,
        "22 Multi-Cloud, Hybrid & Portabilität": 4.0,
        "23 Infrastructure as Code & DataOps": 3.0,
        "24 Monitoring, Observability & AIOps": 2.0,
        "25 API-First & Entwicklerfreundlichkeit": 4.0,
        "26 Cross-Organization Data Sharing": 1.0,
    },
    "OTC": {
        "1 Echtzeit-Datenaufnahme (Real-Time Ingestion)": 3.0,
        "2 Batch-Ingestion & ETL/ELT": 3.0,
        "3 Konnektoren-Ökosystem & Marketplace": 2.0,
        "4 Data-Lakehouse-Architektur": 2.0,
        "5 Datenformat-Flexibilität": 3.0,
        "6 Storage-Tiering & Lifecycle-Management": 4.0,
        "7 Skalierbarkeit (Compute & Storage)": 4.0,
        "8 Stream-Processing & Complex Event Processing": 3.0,
        "9 Analytische Query-Engine": 3.0,
        "10 BI- & Visualisierungs-Integration": 2.0,
        "11 Ad-hoc-Exploration & Notebooks": 3.0,
        "12 ML-Plattform & AutoML": 3.0,
        "13 MLOps, Modell-Lifecycle & Reproduzierbarkeit": 2.0,
        "14 Feature Store": 2.0,
        "15 Generative AI & LLM-Integration": 2.0,
        "16 Modell-Erklärbarkeit & Fairness": 2.0,
        "17 Data Governance, Katalogisierung, Metadaten & Lineage": 3.0,
        "18 Datenqualitätsmanagement": 2.0,
        "19 Sicherheitsarchitektur & Zugriffskontrolle": 4.0,
        "20 Resilienz & Disaster Recovery": 4.0,
        "21 Edge-Computing & lokale Verarbeitung": 2.0,
        "22 Multi-Cloud, Hybrid & Portabilität": 3.0,
        "23 Infrastructure as Code & DataOps": 3.0,
        "24 Monitoring, Observability & AIOps": 3.0,
        "25 API-First & Entwicklerfreundlichkeit": 3.0,
        "26 Cross-Organization Data Sharing": 2.0,
    },
}

country = {
    "AWS": "USA",
    "Azure": "USA",
    "Google Cloud": "USA",
    "STACKIT": "DE",
    "IONOS": "DE",
    "OTC": "DE",
}
