layers = [
    "1 Asset- & Perzeptionslayer (Physicality)",
    "2 Southbound Connectivity (Field Capture)",
    "3 Edge-Integration & Gateway-Layer (Local Logic)",
    "4 Ingestion- & Transport-Layer (IT/OT Bridge)",
    "5 Semantik- & Modellierungslayer (Context)",
    "6 Intelligence- & KI-Integration",
    "7 Governance, Security & Trust (Sovereignty)",
]

scores = {
    "AWS": {
        "1 Asset- & Perzeptionslayer (Physicality)": 4.0,
        "2 Southbound Connectivity (Field Capture)": 4.33,
        "3 Edge-Integration & Gateway-Layer (Local Logic)": 4.0,
        "4 Ingestion- & Transport-Layer (IT/OT Bridge)": 4.67,
        "5 Semantik- & Modellierungslayer (Context)": 3.33,
        "6 Intelligence- & KI-Integration": 5.0,
        "7 Governance, Security & Trust (Sovereignty)": 3.0,
    },
    "Azure": {
        "1 Asset- & Perzeptionslayer (Physicality)": 4.33,
        "2 Southbound Connectivity (Field Capture)": 4.0,
        "3 Edge-Integration & Gateway-Layer (Local Logic)": 4.33,
        "4 Ingestion- & Transport-Layer (IT/OT Bridge)": 5.0,
        "5 Semantik- & Modellierungslayer (Context)": 4.0,
        "6 Intelligence- & KI-Integration": 4.0,
        "7 Governance, Security & Trust (Sovereignty)": 3.67,
    },
    "Google Cloud": {
        "1 Asset- & Perzeptionslayer (Physicality)": 2.0,
        "2 Southbound Connectivity (Field Capture)": 1.67,
        "3 Edge-Integration & Gateway-Layer (Local Logic)": 1.67,
        "4 Ingestion- & Transport-Layer (IT/OT Bridge)": 3.0,
        "5 Semantik- & Modellierungslayer (Context)": 1.33,
        "6 Intelligence- & KI-Integration": 4.0,
        "7 Governance, Security & Trust (Sovereignty)": 3.0,
    },
    "Stackable": {
        "1 Asset- & Perzeptionslayer (Physicality)": 1.0,
        "2 Southbound Connectivity (Field Capture)": 1.0,
        "3 Edge-Integration & Gateway-Layer (Local Logic)": 0.67,
        "4 Ingestion- & Transport-Layer (IT/OT Bridge)": 2.33,
        "5 Semantik- & Modellierungslayer (Context)": 0.67,
        "6 Intelligence- & KI-Integration": 1.0,
        "7 Governance, Security & Trust (Sovereignty)": 1.67,
    },
    "IONOS": {
        "1 Asset- & Perzeptionslayer (Physicality)": 0.33,
        "2 Southbound Connectivity (Field Capture)": 0.67,
        "3 Edge-Integration & Gateway-Layer (Local Logic)": 0.33,
        "4 Ingestion- & Transport-Layer (IT/OT Bridge)": 2.0,
        "5 Semantik- & Modellierungslayer (Context)": 1.0,
        "6 Intelligence- & KI-Integration": 2.5,
        "7 Governance, Security & Trust (Sovereignty)": 3.0,
    },
    "OTC": {
        "1 Asset- & Perzeptionslayer (Physicality)": 1.67,
        "2 Southbound Connectivity (Field Capture)": 3.0,
        "3 Edge-Integration & Gateway-Layer (Local Logic)": 2.0,
        "4 Ingestion- & Transport-Layer (IT/OT Bridge)": 2.67,
        "5 Semantik- & Modellierungslayer (Context)": 1.67,
        "6 Intelligence- & KI-Integration": 2.0,
        "7 Governance, Security & Trust (Sovereignty)": 4.33,
    },
}

country = {
    "AWS": "USA",
    "Azure": "USA",
    "Google Cloud": "USA",
    "Stackable": "DE",
    "IONOS": "DE",
    "OTC": "DE",
}
